# Generated by Django 4.1.9 on 2023-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_alter_fileversion_url_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="file_name",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
